### PR TITLE
do safe pointer arithmetic and check memory bounds of elf image size

### LINKED ISSUE #4056: OE-Fuzzing: Crash detected in /host/sgx/loadelf.c
==5173==ERROR: AddressSanitizer: SEGV on unknown address 0x7f3c74abf1f0 (pc 0x0000006fc3b5 bp 0x7fffcf8885d0 sp 0x7fffcf8883c0 T0)
==5173==The signal is caused by a WRITE memory access.
    #0 0x6fc3b4 in _set_uint64_t_dynamic_symbol_value /openenclave/host/sgx/loadelf.c:724:5
    #1 0x6f2cad in _patch_elf_image /openenclave/host/sgx/loadelf.c:928:5
    #2 0x6ae3e4 in _patch /openenclave/host/sgx/loadelf.c:1174:5
    #3 0x670089 in oe_sgx_build_enclave /openenclave/host/sgx/create.c:929:5
    #4 0x67e76a in oe_create_enclave /openenclave/host/sgx/create.c:1159:5
    #5 0x58f805 in oe_create_create_enclave /src/dynamic/fuzzing/create/host/create_u.c:7291:12
    #6 0x58028e in CreateEnclave(char const*) /../../src/dynamic/fuzzing/create/host/host.cpp:45:14
    #7 0x5810b5 in LLVMFuzzerTestOneInput /../../src/dynamic/fuzzing/create/host/host.cpp:131:19
    #8 0x4577ba in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
    #9 0x4583f5 in fuzzer::Fuzzer::TryDetectingAMemoryLeak(unsigned char const*, unsigned long, bool) /compiler-rt/lib/fuzzer/FuzzerLoop.cpp:608:3
    #10 0x44bed9 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /compiler-rt/lib/fuzzer/FuzzerDriver.cpp:281:6
    #11 0x45095b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /compiler-rt/lib/fuzzer/FuzzerDriver.cpp:709:9
    #12 0x4759f2 in main /compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #13 0x7f3c79d8ebf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #14 0x42dab9 in _start (/home/ragava/Desktop/labs/crashes/create/_patch_elf_image/create_host+0x42dab9)

### PR DESCRIPTION
**Pull request by manojrupireddy**
Fixes #4056 
Signed-off-by: manoj rupireddy <marupire@microsoft.com>

### CODE REVIEW

File: host/sgx/loadelf.c [hunk 1]
```diff
@@ -319,12 +320,14 @@ static oe_result_t _stage_image_segments(
                         "Failed to get segment at index %lu",
                         i);
                 }
-
+                OE_CHECK(segment->vaddr > image->image_size);
```
Comment (anakrish) [inline host/sgx/loadelf.c:323]: OE_CHECK expects oe_result_t

Comment (manojrupireddy) [reply host/sgx/loadelf.c:323]: As condition evaluates to zero, wont the above expression evaluates to OE_OK.

File: host/sgx/loadelf.c [hunk 2]
```diff
@@ -224,9 +224,10 @@ static oe_result_t _initialize_image_segments(
             case PT_LOAD:
                 if (lo > ph->p_vaddr)
                     lo = ph->p_vaddr;
-
-                if (hi < ph->p_vaddr + ph->p_memsz)
-                    hi = ph->p_vaddr + ph->p_memsz;
+                uint64_t temp_hi = hi;
+                OE_CHECK(oe_safe_add_u64(ph->p_vaddr, ph->p_memsz, &temp_hi));
+                if (hi < temp_hi)
+                    hi = temp_hi;
```
Comment (radhikaj) [inline host/sgx/loadelf.c:230]: I think you can just pass hi into oe_safe_add. If there is an overflow, it will fail.

**Review by radhikaj — COMMENTED** [review]
Thanks for getting this fix in!

File: host/sgx/loadelf.c (hunk 2 above)
Comment (manojrupireddy) [reply host/sgx/loadelf.c:230]: hi is updated conditionally only if new high is greater than previous  hi. o i think temp variable is required.

File: host/sgx/loadelf.c [hunk 3]
```diff
@@ -720,7 +729,9 @@ static oe_result_t _set_uint64_t_dynamic_symbol_value(
     if (elf64_find_dynamic_symbol_by_name(&image->elf, name, &sym) != 0)
         goto done;
 
-    symbol_address = (uint64_t*)(image->image_base + sym.st_value);
+    OE_CHECK(sym.st_value > image->image_size);
```
Comment (radhikaj) [inline host/sgx/loadelf.c:732]: Why did you add this check?

File: host/sgx/loadelf.c [hunk 4]
```diff
@@ -909,9 +920,11 @@ static oe_result_t _patch_elf_image(
     oe_sgx_enclave_properties_t* oeprops;
     oe_enclave_module_info_t* module_info;
     uint64_t enclave_rva = 0;
-
-    oeprops =
-        (oe_sgx_enclave_properties_t*)(image->image_base + image->oeinfo_rva);
+    uint64_t oeprops_address = 0;
+    OE_CHECK(image->oeinfo_rva > image->image_size);
```
Comment (radhikaj) [inline host/sgx/loadelf.c:924]: Why is this check necessary?

File: host/sgx/loadelf.c [hunk 5]
```diff
@@ -977,11 +990,17 @@ static oe_result_t _patch_elf_image(
...
-        OE_CHECK(
-            _get_dynamic_symbol_rva(image, "_module_info", &module_info_rva));
-        module_info =
-            (oe_enclave_module_info_t*)(image->image_base + module_info_rva);
+        size_t module_info_rva_offset = 0;
+        uint64_t module_info_rva_address = 0;
+
+        OE_CHECK(_get_dynamic_symbol_rva(
+            image, "_module_info", &module_info_rva_offset));
+        OE_CHECK(module_info_rva_offset > image->image_size);
```
Comment (radhikaj) [inline host/sgx/loadelf.c:998]: Why is this check there?

File: host/sgx/loadelf.c [hunk 6]
```diff
@@ -1224,12 +1246,17 @@ static oe_result_t _sgx_load_enclave_properties(
     oe_sgx_enclave_properties_t* properties)
 {
     oe_result_t result = OE_UNEXPECTED;
-
+    uint64_t oeinfo_start_address = 0;
+    OE_CHECK(image->elf.oeinfo_rva > image->elf.image_size);
```
Comment (radhikaj) [inline host/sgx/loadelf.c:1250]: Is this check needed?

File: host/sgx/loadelf.c [hunk 7]
```diff
@@ -1244,15 +1271,27 @@ static oe_result_t _sgx_update_enclave_properties(
 {
     oe_result_t result = OE_UNEXPECTED;
 
+    uint64_t elf_oeinfo_pos = 0;
+    uint64_t elf_image_oeinfo_pos = 0;
+    OE_CHECK(image->elf.oeinfo_file_pos > (uint64_t)image->elf.elf.size);
```
Comment (radhikaj) [inline host/sgx/loadelf.c:1276]: Just go through and see if the checks you have introduced to compare these variables is necessary. It might be, I just cant figure it out.

File: host/sgx/loadelf.c (hunk 1 above)
Comment (radhikaj) [reply host/sgx/loadelf.c:323]: @manojrupireddy , I think there might be additional warnings with this implicit cast.

File: host/sgx/loadelf.c (hunk 7 above)
Comment (manojrupireddy) [reply host/sgx/loadelf.c:1276]: As part of fuzzing, program headers can be corrupted and forced to increase offset beyond image size. This check catches such issues. Critically looking such elf image fuzzing could be detected if signing infrastructure is working as expected and we don't need above checks. The issue #4056 is a similar kind of issue where fuzzing  forced offsets to move beyond image size and these checks catches them. If we rely on signing tools infrastructure, we can remove such checks. One more catch is that image_size itself could be corrupted as part of fuzzing as discussed in the issue #4058. Hence, I am also not completely confident on adding these checks here. @mingweishih @anakrish @mrragava  can you add your comments and see if these checks are required.

File: host/sgx/loadelf.c (hunk 1 above)
Comment (anakrish) [reply host/sgx/loadelf.c:323]: Using OE_CHECK for a conditional expression is hard to read. 
Do you expect the condition to evaluate to false?

Comment (mingweishih) [reply host/sgx/loadelf.c:323]: BTW, can you explain what's this check for?

File: host/sgx/loadelf.c (hunk 3 above)
Comment (mingweishih) [reply host/sgx/loadelf.c:732]:
```suggestion
    if (sym.st_value <= image->image_size)
        OE_RAISE(OE_INVALID_PARAMETER);
```
Also, please explain what's the check for.

File: host/sgx/loadelf.c (hunk 4 above)
Comment (mingweishih) [reply host/sgx/loadelf.c:924]: Use the if + OE_RAISE pattern.

File: host/sgx/loadelf.c (hunk 5 above)
Comment (mingweishih) [reply host/sgx/loadelf.c:998]: Use the if + OE_RAISE pattern.

File: host/sgx/loadelf.c (hunk 6 above)
Comment (mingweishih) [reply host/sgx/loadelf.c:1250]: Use the if + OE_RAISE pattern.

File: host/sgx/loadelf.c (hunk 7 above)
Comment (mrragava) [reply host/sgx/loadelf.c:1276]: @manojrupireddy ELF parsers should limit the trust only to image_size, All the other offsets should treat image_size as base line. Even if the image_size is tampered by fuzzer the offsets calculated should not add-up beyond the allocated (image_size) image region.

**Comment by anakrish** [comment]
@manojrupireddy Can you let me know when this is ready for review again?

**Comment by manojrupireddy** [comment]
bors try

**Review by anakrish — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]
