### PR TITLE
Dynamically load sgx_enclave_common

### LINKED ISSUE #3127: Build without libsgx-enclave-common-dev on non-SGX machines for simulation only
I'm trying to follow the scenario of point 3 in https://github.com/openenclave/openenclave/tree/master/scripts/ansible#open-enclave-deployment-options-via-ansible. This doesn't install any SGX libraries. However, trying to build OE (with `-DHAS_QUOTE_PROVIDER=OFF`) fails with "Intel SGX EnclaveCommonAPI library not found, aborting!". `libsgx-enclave-common-dev` shouldn't be needed for simulation mode.

My concrete use case is to get [LGTM](https://lgtm.com) code analysis working for an OE project. The service requires to build the code but doesn't allow to install apt dependencies from non-official channels. This is why I can't install the Intel SGX libraries (not that it would make sense anyway).

Earlier discussion: https://github.com/openenclave/openenclave/issues/2252.

### PR DESCRIPTION
**Pull request by anakrish**
OE SDK can now be built for Simulation Mode on non SGX x64 systems
by passing HAS_QUOTE_PROVIDER=off

Simulation mode does not require SGX libraries to be present in the system.

Note: OE SDK debian packages will still have dependencies on SGX packages. It is safe to install SGX packages on non SGX machines.

Addresses the technical/implementation aspect of the following issues; documentation needs to be updated
- #2717
- #2728
- #1983
- #3127 

I have manually verified that this PR fixes #3127 
On a fresh Ubuntu 18.04 non SGX VM
```bash
sudo apt update
git clone --recursive https://github.com/anakrish/openenclave
cd openenclave
sudo scripts/ansible/install-ansible.sh
sudo ansible-playbook scripts/ansible/oe-vanilla-prelibsgx-setup.yml 
mkdir build
cd build
cmake .. -DHAS_QUOTE_PROVIDER=off
make -j 16
OE_SIMULATION=1 ctest
```

fixes #3217

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

### CODE REVIEW

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try

File: host/sgx/sgx_enclave_common_wrapper.c [hunk 1]
```diff
@@ -0,0 +1,207 @@
...
+    else
+    {
+        OE_TRACE_ERROR("Failed to load %s\n", LIBRARY_NAME);
+        goto done;
+    }
+
+done:
+    if (result != OE_OK)
+    {
+        // If is catastrophic error if sgx_enclave_common library cannot be
```
Comment (radhikaj) [inline host/sgx/sgx_enclave_common_wrapper.c:135]:
```suggestion
        // It is a catastrophic error if sgx_enclave_common library cannot be
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,9 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Added
 - Added `oe_sgx_get_signer_id_from_public_key()` function which helps a verifier of SGX
   reports extract the expected MRSIGNER value from the signer's public key PEM certificate.
+- OE SDK can now be built for Simulation Mode on non SGX x64 systems by passing HAS_QUOTE_PROVIDER=off.
+  This is enabled by dynamically loading SGX Enclave Common Library instead of linking it into
+  the host application.
```
Comment (radhikaj) [inline CHANGELOG.md:18]: Can we reflect what end users will see as well?
  the host application. Users installing the SDK packages on non SGX X64 systems will be able to run the helloworld, switchless and fileencryptor samples in simulation mode.

File: CHANGELOG.md [hunk 3]
```diff
@@ -13,6 +13,9 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Added
 - Added `oe_sgx_get_signer_id_from_public_key()` function which helps a verifier of SGX
   reports extract the expected MRSIGNER value from the signer's public key PEM certificate.
+- OE SDK can now be built for Simulation Mode on non SGX x64 systems by passing HAS_QUOTE_PROVIDER=off.
```
Comment (dthaler) [inline CHANGELOG.md:16]: As worded, "built for Simulation Mode" sounds like you cannot use simulation mode at all without building this way.  Did you mean "built to run only on Simulation Mode"?

Also, I'm curious why you have to build it differently in the first place. If you have to have an SGX capable machine to _build_ on, that should be explained somewhere, since that is very surprising. Is that answered in some other doc?

Comment (anakrish) [reply CHANGELOG.md:16]: How about:
" OE SDK can now be built on a non SGX x64 Windows machine by passing HAS_QUOTE_PROVIDER=off. Previously this was not possible due to the hard dependency on sgx_enclave_common.dll which is available only on SGX machines."

The biggest impact this PR has is on the Windows experience. Previously building the SDK had a hard-dependency on sgx_enclave_common.dll which is installed via Windows Update only on SGX machines.

> If you have to have an SGX capable machine to build on, that should be explained somewhere, since that is very surprising

All our GettingStarted docs for Contributors list an SGX1 capable machine as a prerequisite.

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try-

File: CHANGELOG.md (hunk 2 above)
Comment (anakrish) [reply CHANGELOG.md]: I have reworded it to indicate the user experience.

File: host/sgx/sgx_enclave_common_wrapper.c (hunk 1 above)
Comment (anakrish) [reply host/sgx/sgx_enclave_common_wrapper.c]: Fixed.

File: CHANGELOG.md (hunk 3 above)
Comment (anakrish) [reply CHANGELOG.md]: I have reworded the changelog entry.

**Comment by anakrish** [comment]
bors try

File: CHANGELOG.md (hunk 3 above)
Comment (dthaler) [reply CHANGELOG.md]: > All our GettingStarted docs for Contributors list an SGX1 capable machine as a prerequisite.

Good point.  Shouldn't this PR then update those docs?

Comment (dthaler) [reply CHANGELOG.md]: I just found PR #3158

Comment (anakrish) [reply CHANGELOG.md]: This is the most recent changelog description
`OE SDK can now be built and run in simulation mode on a non SGX x64 Windows machine by passing HAS_QUOTE_PROVIDER=off.
  Previously, the build would work, but running applications would fail due to missing sgx_enclave_common.dll.`

I have added a doc (#3155) for the  workflow that this PR enables - build the SDK for on non SGX x64 Windows machines and run Simulation Mode. Previously that was not possible.

As to 
>> All our GettingStarted docs for Contributors list an SGX1 capable machine as a prerequisite.

> Good point. Shouldn't this PR then update those docs?

We are not yet there. But making good progress towards it. An official build of the SDK does not use HAS_QUOTE_PROVIDER=off  (ie it requires HAS_QUOTE_PROVIDER=on) and does indeed require an SGX machine currently.

Comment (anakrish) [reply CHANGELOG.md]: I believe this PR also addressed the technical aspect of #2717 #2728 #1983. But I need to carefully read those issues and then write the missing documentation. Hence I'm trying to get the source code changes in first.

**Comment by anakrish** [comment]
bors try

**Comment by anakrish** [comment]
bors try
