### PR TITLE
Drop opt_params condition for ECDSA/EPID case

### LINKED ISSUE #3742: Attestation sample fails when running with quote-ex library installed
Repro steps
1. Install quote-ex package (sudo apt -y install libsgx-quote-ex)
2. run [attestation sample](https://github.com/openenclave/openenclave/tree/master/samples/attestation)

Result:
Invalid parameter error

```
2020-11-19T02:05:23+0000.432742Z [(H)ERROR] tid(0x7fdb7330ac00) | :OE_INVALID_PARAMETER [/source/host/sgx/sgxquote.c:oe_sgx_qe_get_quote:604]
2020-11-19T02:05:23+0000.432781Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:oe_get_remote_report:305]
2020-11-19T02:05:23+0000.432793Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:_oe_get_report_internal:384]
2020-11-19T02:05:23+0000.432805Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/core/sgx/report.c:oe_get_report_v2_internal:457]
2020-11-19T02:05:23+0000.432819Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed:SGX Plugin: Failed to get OE report. OE_INVALID_PARAMETER (oe_result_t=OE_INVALID_PARAMETER) [/source/enclave/sgx/attester.c:_get_evidence:173]
2020-11-19T02:05:23+0000.432829Z [(E)ERROR] tid(0x7fdb7330ac00) | enclave_a.signed::OE_INVALID_PARAMETER [/source/enclave/attest_plugin.c:oe_get_evidence:116]
```

### PR DESCRIPTION
**Pull request by ryanhsu19**
Drop the `opt_params` condition to resolve the issue where the attestation sample could not be run after installing quote-ex library.

Fix #3742 .

Signed-off-by: Ryan Hsu <ryhsu@microsoft.com>

### CODE REVIEW

File: host/sgx/sgxquote.c [hunk 1]
```diff
@@ -708,8 +708,9 @@ oe_result_t oe_sgx_qe_get_quote(
         }
         else // ECDSA
         {
-            // For EPID, no opt_params is taken.
-            if (opt_params || opt_params_size)
+            // For EPID, no opt_params is taken, and opt_params_size should be
+            // zero.
+            if (opt_params_size > 0)
```
Comment (mingweishih) [inline host/sgx/sgxquote.c:713]: `opt_params_size` has type `size_t` thus can never be negative.

```suggestion
            if (opt_params_size)
```

File: host/sgx/sgxquote.c [hunk 2]
```diff
@@ -708,8 +708,9 @@ oe_result_t oe_sgx_qe_get_quote(
         }
         else // ECDSA
         {
-            // For EPID, no opt_params is taken.
-            if (opt_params || opt_params_size)
+            // For EPID, no opt_params is taken, and opt_params_size should be
```
Comment (mingweishih) [inline host/sgx/sgxquote.c:711]: The comments now do not seem to reflect the if statement below. Can you also update it?

**Comment by ryanhsu19** [comment]
Thanks!

**Review by yentsanglee — APPROVED** [review]

**Review by mingweishih — APPROVED** [review]
LGTM
