### PR TITLE
Mark server is ready when it fails to initialize in the tls_e2e test

### LINKED ISSUE #2414: Unit test "tls_e2e" hangs on win19
**Environment**
- AccImage: windows-server-2019
- VmSize: Standard_DC2s
- Debug build

**Test Output**
```
test 82
        Start  82: tests/tls_e2e

82: Test command: C:\Users\feliu\workspace\openenclave\build\x64-Debug\tests\tls_e2e\host\tls_e2e_host.exe "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/server_enc/tls_server_enc" "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/client_enc/tls_client_enc"
82: Test timeout computed to be: 10000000
82: Test case: Server:
82: ------positive_test
82:  This is a positive test case. Expect no errors
82: 2020-01-08T07:28:13.000000Z [(H)ERROR] tid(0x75c) | quote3_error_t=0xe035
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\host\sgx\sgxquote.c:oe_sgx_qe_get_target_info:21]
82: 2020-01-08T07:28:13.000000Z [(H)ERROR] tid(0x75c) | :OE_PLATFORM_ERROR [..\..\host\sgx\quote.c:sgx_get_qetarget_info:31]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_remote_report:182]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:_oe_get_report_internal:276]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_report_v2:329]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:oe_get_report failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\enclave\tls_cert.c:oe_generate_attestation_certificate:148]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc: failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\tests\tls_e2e\common\utility.cpp:generate_certificate_and_pkey:126]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:failed with OE_PLATFORM_ERROR
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:configure_server_ssl:126]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc: failed
82:   ! Configure server SSL settings: configure_server_ssl returned 1
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:259]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:Last error was: 1 - UNKNOWN ERROR CODE (0001)
82:
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:413]
```

**Questions**
- I was able to reproduce this error in multiple VMs. Was this test passing in our CI/CD?
- How long is 10000000 timeout? If it is too long, shall we shorten it?

### PR DESCRIPTION
**Pull request by jhand2**
The tls_e2e test currently deadlocks if it fails to initialize the server because it never marks the tls server as ready. On server init failure, mark the server as ready so that the client continues execution.

Fixes #2414

### CODE REVIEW

**Comment by jhand2** [comment]
bors try

File: tests/tls_e2e/host/host.cpp [hunk 1]
```diff
@@ -237,7 +250,12 @@ int run_test_with_config(tls_test_configs_t* test_configs)
     {
         // Release lock on scope exit
         std::unique_lock<std::mutex> server_lock(g_server_mutex);
-        g_server_cond.wait(server_lock, [] { return g_server_condition; });
+        g_server_cond.wait(
+            server_lock, [] { return g_server_initialization_done; });
+        if (!g_server_initialization_success)
+        {
+            return g_server_thread_exit_code;
```
Comment (CodeMonkeyLeet) [inline tests/tls_e2e/host/host.cpp]: Consider adding an `OE_TRACE_INFO/ERROR()` here to log the server failure; it can be confusing since this only used to return the `g_client_thread_exit_code` to differentiate between the two without some disambiguation.

**Comment by jhand2** [comment]
bors try
