### PR TITLE
Check the source alignment in memcpy_with_barrier

### LINKED ISSUE #4540: Undefined behaviour in `oe_memcpy_with_barrier`
We're trying to track down some instability that appears to have been introduced after upgrading to OE 0.18.0.

I found some undefined behaviour in the implementation of `oe_memcpy_with_barrier`:

```
../src/ds/ccf_memcpy.h:114:7: runtime error: load of misaligned address 0x7ffdd73dd051 for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x7ffdd73dd051: note: pointer points here
 69 6e 74  65 72 66 61 63 65 00 be  a2 56 8f 00 00 00 00 00  0e 36 e0 45 00 00 00 00  c1 cd 9d 00 00
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/ds/ccf_memcpy.h:114:7 in 
```

This is copied locally to run through sanitizers, the actual source is [here](https://github.com/openenclave/openenclave/blob/d8e6c143eef73bce8306960c874b694e5317e02e/enclave/core/sgx/writebarrier.c#L201).

Are any sanitizers run on the OE codebase?

### PR DESCRIPTION
**Pull request by mingweishih**
This PR ensures the alignment of the source when doing 4- and 2-byte write in the `memcpy_with_barrier`

Fixes #4540 

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

File: enclave/core/sgx/writebarrier.c [hunk 1]
```diff
@@ -5,6 +5,8 @@
 #include <openenclave/enclave.h>
 #include <openenclave/internal/raise.h>
 
+#include <openenclave/internal/print.h>
```
Comment (anakrish) [inline enclave/core/sgx/writebarrier.c:8]: This include does not seem related to this PR.

**Review by anakrish — COMMENTED** [review]
For how many of our edge functions does this turn off the optimization?

If it turns off for most cases, then we might not gain anything by having the optimization code.

File: enclave/core/sgx/writebarrier.c (hunk 1 above)
Comment (mingweishih) [reply enclave/core/sgx/writebarrier.c]: Fixed. This was for verifying the fix.

**Comment by mingweishih** [comment]
> For how many of our edge functions does this turn off the optimization?
> 
> If it turns off for most cases, then we might not gain anything by having the optimization code.

Here are some statistics based on our test:

Before the fix
1-byte write count: 48
2-byte write count: 48
4-byte write count: 50

After the fix
1-byte write count: 48
2-byte write count: 48
4-byte write count: 50

As we can see, the change generally does not affect the distribution of the each write, but only their order.

Assuming both the source (0x1001) and the destination are 7-byte-offset from the 8-byte alignment, the original order will be

4-byte read at 0x1001
-> 2-byte read at 0x1005
-> 1-byte read at 0x1007

With the fix, the order becomes

1-byte read at 0x1001
-> 2-byte read at 0x1002
-> 4-byte read at 0x1004

In the worse case scenario (which we does not see in the test), the original 4-byte write could turn into 1-byte -> 2-byte -> 1-byte sequence. However, this should still better than four 1-byte write.

**Review by anakrish — APPROVED** [review]
LGTM. Nice description of the performance behavior of the fix.
