### PR TITLE
Fixed bug in issue #2807 and found the end of tcbList correctly

### LINKED ISSUE #2807: _read_tcb_info not handle "]" properly
In [sgx/tcbinfo.c](https://github.com/openenclave/openenclave/blob/master/common/sgx/tcbinfo.c), the function `oe_parse_tcb_info_json` calls `_read_tcb_info` to read json tcbinfo. `_read_tcb_info` will:
1. parse the tcbinfo parameters before the `tcbLevels`
2. call `_read_tcb_info_tcb_level_v2` to read tcbs in a while loop until find the best match tcb in `tcbLevels` and load it to `platform_tcb_level`
3. skip the rest tcbs in `tcbLevels` and move parser's `itr` pointer to the end of it which is marked by a ']' as the list is enclosed by `[]`.
Then `itr` should point at the begining of the `signature` parameter, waited to be processed by the caller function `oe_parse_tcb_info_json`.

Current design treats the first `]` after the tcb match as the end of `tcbLevels`. The issue is, each tcb entry inside the `tcbList` could have a field `advisoryIDs`, whose value is a list and enclosed by `[]`. One example is [here](https://github.com/openenclave/openenclave/blob/master/tests/report/data_v2/tcbInfoAdvisoryIds.json). 
**So, `]` cannot be treated as the only end mark of `tcbLevels`.**
If no entry or only the matched tcb entry contains an `advisoryIDs`, `_read_tcb_info_tcb_level_v2` in step 2 will parse the entire `advisoryIDs` and the `itr` pointer will surpass the `]` in `advisoryIDs` field. Thus, it will not cause any trouble. This is why it passed current test cases.
However, if the any other tcb entry also contains the `advisoryIDs` and a `]`. Then step 3 will end at that first met `]` in `advisoryIDs`, ahead of the true end of `tcbLists` incorrectly and the following `Reading signature` function in caller `oe_parse_tcb_info_json` will cause an error. This bug is verified when I added an `advisoryIDs` field to any unmatched tcb entry like this:
```
{
  "tcbInfo": {
    "version": 2,
    "issueDate": "2018-06-06T10:12:17Z",
    "nextUpdate": "2019-06-06T10:12:17Z",
    "fmspc": "00906EA10000",
    "tcbType": 0,
    "tcbEvaluationDataNumber":5,
    "tcbLevels": [
      {
        "tcb":{
          "sgxtcbcomp01svn": 4,
          "sgxtcbcomp02svn": 4,
          "sgxtcbcomp03svn": 2,
          "sgxtcbcomp04svn": 4,
          "sgxtcbcomp05svn": 1,
          "sgxtcbcomp06svn": 128,
          "sgxtcbcomp07svn": 1,
          "sgxtcbcomp08svn": 1,
          "sgxtcbcomp09svn": 1,
          "sgxtcbcomp10svn": 1,
          "sgxtcbcomp11svn": 1,
          "sgxtcbcomp12svn": 1,
          "sgxtcbcomp13svn": 1,
          "sgxtcbcomp14svn": 1,
          "sgxtcbcomp15svn": 1,
          "sgxtcbcomp16svn": 1,
          "pcesvn":6
        },
        "tcbDate":"2018-01-04T01:02:03Z",
        "tcbStatus":"UpToDate",
        // matched entry, step 2 will pass it and cause no trouble
        "advisoryIDs":["INTEL-SA-00079", "INTEL-SA-00076"]    
      },
        // while loop ends and step 3 starts from here
      {
        "tcb": {
          "sgxtcbcomp01svn": 4,
          "sgxtcbcomp02svn": 4,
          "sgxtcbcomp03svn": 2,
          "sgxtcbcomp04svn": 4,
          "sgxtcbcomp05svn": 1,
          "sgxtcbcomp06svn": 128,
          "sgxtcbcomp07svn": 1,
          "sgxtcbcomp08svn": 1,
          "sgxtcbcomp09svn": 1,
          "sgxtcbcomp10svn": 1,
          "sgxtcbcomp11svn": 1,
          "sgxtcbcomp12svn": 1,
          "sgxtcbcomp13svn": 1,
          "sgxtcbcomp14svn": 1,
          "sgxtcbcomp15svn": 1,
          "sgxtcbcomp16svn": 1,
          "pcesvn": 5
        },
        "tcbDate":"2018-01-04T01:02:03Z",
        "tcbStatus": "OutOfDateConfigurationNeeded",
        // unmatched entry, cause itr stop here, incorrectly early
        "advisoryIDs":["INTEL-SA-00079", "INTEL-SA-00076"]    
      },
      {
        "tcb": {
          "sgxtcbcomp01svn": 2,
          "sgxtcbcomp02svn": 2,
          "sgxtcbcomp03svn": 2,
          "sgxtcbcomp04svn": 4,
          "sgxtcbcomp05svn": 1,
          "sgxtcbcomp06svn": 128,
          "sgxtcbcomp07svn": 1,
          "sgxtcbcomp08svn": 1,
          "sgxtcbcomp09svn": 1,
          "sgxtcbcomp10svn": 1,
          "sgxtcbcomp11svn": 1,
          "sgxtcbcomp12svn": 1,
          "sgxtcbcomp13svn": 1,
          "sgxtcbcomp14svn": 1,
          "sgxtcbcomp15svn": 1,
          "sgxtcbcomp16svn": 1,
          "pcesvn": 4
        },
        "tcbDate":"2018-01-04T01:02:03Z",
        "tcbStatus": "ConfigurationNeeded"
      },
      {
        "tcb": {
          "sgxtcbcomp01svn": 2,
          "sgxtcbcomp02svn": 2,
          "sgxtcbcomp03svn": 2,
          "sgxtcbcomp04svn": 4,
          "sgxtcbcomp05svn": 1,
          "sgxtcbcomp06svn": 128,
          "sgxtcbcomp07svn": 1,
          "sgxtcbcomp08svn": 1,
          "sgxtcbcomp09svn": 1,
          "sgxtcbcomp10svn": 1,
          "sgxtcbcomp11svn": 1,
          "sgxtcbcomp12svn": 1,
          "sgxtcbcomp13svn": 1,
          "sgxtcbcomp14svn": 1,
          "sgxtcbcomp15svn": 1,
          "sgxtcbcomp16svn": 1,
          "pcesvn": 3
        },
        "tcbDate":"2018-01-04T01:02:03Z",
        "tcbStatus": "OutOfDate"
      },
      {
        "tcb": {
          "sgxtcbcomp01svn": 2,
          "sgxtcbcomp02svn": 2,
          "sgxtcbcomp03svn": 2,
          "sgxtcbcomp04svn": 4,
          "sgxtcbcomp05svn": 1,
          "sgxtcbcomp06svn": 128,
          "sgxtcbcomp07svn": 1,
          "sgxtcbcomp08svn": 1,
          "sgxtcbcomp09svn": 1,
          "sgxtcbcomp10svn": 1,
          "sgxtcbcomp11svn": 1,
          "sgxtcbcomp12svn": 1,
          "sgxtcbcomp13svn": 1,
          "sgxtcbcomp14svn": 1,
          "sgxtcbcomp15svn": 1,
          "sgxtcbcomp16svn": 1,
          "pcesvn": 2
        },
        "tcbDate":"2018-01-04T01:02:03Z",
        "tcbStatus": "Revoked"
      }
    ]
  },
  "signature": "62d181c4ba863213b825d1c0b66b92a3dbdb27b8ff7c7250cb2b2ab87a8f90d5e5a1416914369d8f82c56cd3d875caa54ae4b917caf4af7a93dec52067cbfd7b"
}
```
Besides, in the future, if new fields are added to tcbinfo json which include `[]`, it will also cause the same problem. We need to change the current logic that determines the end of `tcbLevel` list.

### PR DESCRIPTION
**Pull request by qiucwang**
Fixes #2807 
The issue 2807 points out a bug that the end of `tcbLists` is incorrectly marked by the first `]` after the matched tcb entry. It will make `itr` stop earlier than the end of `tcbList`, and cause an error for the following signature reading. Instead `itr` would stops at any `]` inside a tcb entry, such as the end of AdvisoryIDs value which is enclosed by `[]`.
To verify this, I modify a test case `tests/report/data_v2/tcbInfoAdvisoryIds.json.` and added an `AdvisoryIDs` field in one unmatched tcb entry. And current design threw a bug:
```
2020-04-08T18:09:53.000000Z [(E)ERROR] tid(0x7ffff7fa5740) | report_enc::OE_JSON_INFO_PARSE_ERROR [../common/sgx/tcbinfo.c:_read_property_name_and_colon:175]
2020-04-08T18:09:53.000000Z [(E)ERROR] tid(0x7ffff7fa5740) | report_enc::OE_JSON_INFO_PARSE_ERROR [../common/sgx/tcbinfo.c:oe_parse_tcb_info_json:679]
Test failed: ../tests/report/host/tcbinfo.cpp(464): TestVerifyTCBInfoV2_AdvisoryIDs ecall_result == OE_OK
```
```
// oe_parse_tcb_info_json:679:
OE_TRACE_VERBOSE("Reading signature");
OE_CHECK(_read_property_name_and_colon("signature", &itr, end));
```

Debug into itr, it's not stop at the end of tcb entry and beginning of signature field.
```
itr: "{\n        \"tcb\": {\n          \"sgxtcbcomp"...
```

And I fixed bug by introducing a variable square_bracket_count initialized as 0. After a tcb match and process tries to move `itr` to the end of `tcbList`, the square_bracket_count will increase by 1 each time read a `[` and decrease by 1 each time read a `]`. So `itr` will stop only when it reads a `]` as well as square_bracket_count has been balanced back to 0. And that will handle all the `[]` cases inside the `tcbList` and skip those `]`.

After the fixing, it passed the modified test case and debug into itr, it stop at the beginning of signature field correctly.
```
itr:  "\"signature\":\"...
```

### CODE REVIEW

File: common/sgx/tcbinfo.c [hunk 1]
```diff
@@ -502,6 +502,7 @@ static oe_result_t _read_tcb_info(
     uint64_t value = 0;
     const uint8_t* date_str = NULL;
     size_t date_size = 0;
+    uint64_t square_bracket_count;
```
Comment (yentsanglee) [inline common/sgx/tcbinfo.c:505]: Initialize it, like other variables around.

Comment (qiucwang) [reply common/sgx/tcbinfo.c]: Fixed. Thanks!
