### PR TITLE
Remove COMPILE_SYSTEM_EDL cmake option

### LINKED ISSUE #3362: Build fails with Clang and -DCOMPILE_SYSTEM_EDL=ON
```
FAILED: host/CMakeFiles/oehost.dir/syscall_u_wrapper.c.o 
/usr/bin/clang-7 -DOE_API_VERSION=2 -DOE_BUILD_UNTRUSTED -DOE_LINK_SGX_DCAP_QL -DOE_REPO_BRANCH_NAME=\"\" -DOE_REPO_LAST_COMMIT=\"6046f509e92acab3e358d325a5f600bb1556cfc8\" -DOE_USE_BUILTIN_EDL -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -Ihost -I../include -Ioutput/include -O3 -DNDEBUG   -mllvm -x86-speculative-load-hardening -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -Wno-type-limits -mxsave -Wno-attributes -Wmissing-prototypes -fPIC -m64 -fstack-protector-strong -std=gnu11 -MD -MT host/CMakeFiles/oehost.dir/syscall_u_wrapper.c.o -MF host/CMakeFiles/oehost.dir/syscall_u_wrapper.c.o.d -o host/CMakeFiles/oehost.dir/syscall_u_wrapper.c.o   -c ../host/syscall_u_wrapper.c
../host/syscall_u_wrapper.c:23:20: error: unused function '_call_enclave_function' [-Werror,-Wunused-function]
static oe_result_t _call_enclave_function(
                   ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by mingweishih**
This PR removes the `COMPILE_SYSTEM_EDL` cmake option that we no longer support. Also, the PR cleans up the code that associates with the option. The detail of the changes is as follows.

- Remove `*_wrapper_t.c` and `*_wrapper_u.c` files that were used to support internal system edl implementation.
- Remove the use of multiple ecall/ocall tables that were used to store tables per wrapper.
- Remove `call_by_table_id` internal functions. Now we maintain only a single ocall/ecall table. The ecall/ocall dispatching is no longer have the table id look-up logic.
- Remove the `OE_USE_BUILTIN_EDL` compilation definition that represents the value of `COMPILE_SYSTEM_EDL`

Fixes #3362 

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

File: enclave/core/malloc.c [hunk 1]
```diff
@@ -32,6 +32,9 @@
 
 #endif
 
+/* If true, disable the debug malloc checking */
+bool oe_disable_debug_malloc_check;
```
Comment (anakrish) [inline enclave/core/malloc.c:36]: Is this part of this PR?

Comment (mingweishih) [reply enclave/core/malloc.c:36]: The declaration was put in the enclave/core/calls.c, which is removed in this PR. I find moving to this file is fine (otherwise we will have a file that does only this variable declaration.). Do you have any suggestion?

Comment (anakrish) [reply enclave/core/malloc.c:36]: Ah Ok. I didn't realize it was a preexiting variable that is being moved.
This is the right place for the variable.

**Comment by mingweishih** [comment]
bors try

**Comment by BRMcLaren** [comment]
ignore me

**Comment by BRMcLaren** [comment]
bors try

**Comment by jhand2** [comment]
woohoo! Thanks!
