### PR TITLE
Use thread safe script to generate oecert pubkey header

### LINKED ISSUE #3980: gen_pubkey_header.sh is not thread-safe
When building the OE SDK with multi-threading, the content of `oecert_enc_pubkey.h` generated by the `gen_pubkey_header.sh` could be out-of-order, which is due to that the gen_pubkey_header.sh uses multiple read/write operations that may not be thread-safe.

Steps for reproduce:
build the SDK with `make -j8` (may require a couple of retries)

An example of wrong output:
```
// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#ifndef OECERT_PUBKEY_H
#define OECERT_PUBKEY_H

static const char OECERT_ENC_PUBLIC_KEY[] =
    "4Wfrkehl/CY/4B5ksLmH4sz+bm1oOrT0bSgV3m2SeQ+bAgED\n"
    "-----BEGIN PUBLIC KEY-----\n"
    "-----END PUBLIC KEY-----\n";

#endif /* OECERT_ENC_PUBLIC_KEY */

    "MIIBoDANBgkqhkiG9w0BAQEFAAOCAY0AMIIBiAKCAYEAzoG5zogYhasZ1tx3fIzI\n"
    "XOEvVxIs1Z4Nm0S6/DnXjtX4XHxITTE1X+0Ir10w/3817yUWk33FjimSJYJ1Sjkr\n"
    "J0pPQOpZiEWl2ms1mPQrNOu4K5GPezNRdVORKSyV+njsoGLHRxbP4oNa6xuLeB3p\n"
    "pqR+Lf5OFgCvAl9IQXl3xzD1S9IDzBTXtpvdSTgT57mqWI1mEHptsnXulYi346IY\n"
    "goi2rk4gNXeslBak53pQ3CaxzluZbbxuJZ3ehM1+DpgSYW3WK6pOTfudCWCbrpQQ\n"
    "Rw8gkqJdxwjVxpjpchMnLPqLlQg7BfxNVzJnp6AIZqFUWZJL0OCp+l3p6K5UzxGf\n"
    "CJaYiwPHtNEcHiXha0XI9q8oz4qGt79rmE8+tQ2a9A3iE5vdfd6Bd0DliLIYGGNS\n"
    "zDNxvIwO1vDs5wwQwzZvJpKLL2vGKkCoUp+ZSmKVKCC0VK/4YCsYwNWO1Ih9vEtD\n"
    "4Wfrkehl/CY/4B5ksLmH4sz+bm1oOrT0bSgV3m2SeQ+bAgED\n"
    "-----END PUBLIC KEY-----\n";

#endif /* OECERT_ENC_PUBLIC_KEY */
```

Expected output:
```
// Copyright (c) Open Enclave SDK contributors.
// Licensed under the MIT License.

#ifndef OECERT_PUBKEY_H
#define OECERT_PUBKEY_H

static const char OECERT_ENC_PUBLIC_KEY[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MIIBoDANBgkqhkiG9w0BAQEFAAOCAY0AMIIBiAKCAYEA3xzJr6W4Mpi6YgSOoUTq\n"
    "rQ7o2QhEC+gw03FAeBdtz/dKS+LE8WX/haGKQEdzE0Hc1CjKceHhyM7Onea5ycsJ\n"
    "/jByxrdZnrmitkK6P9X0lrRSzWWre1SAkioC+iJqEe3U5KUeRyi1u7j6+0RNffI7\n"
    "zbqPndg/LlmwvZ8AY6MRtVADMTh9RXPQUfT/e8rheKZnHLyjV8Qhjr5lkfpza7pB\n"
    "kQBVC5/fKc62kkI7ec72etzWfLy9HZpgjbz07Wwin2qN+1MZzvSgR3IEM3tKcbc4\n"
    "ZX7Ru5+dFxE/YJmGg5LSU6hLdUmgDyRIwu622nP1sEvXM8yZtRCl3lHoGZe+eBMK\n"
    "9lqj6vIT3xe5+LetP4WJkPEjOa6NMlMlZKs6i2YuR4wUbSQaO4BQmsyCjWbtYe3P\n"
    "Hi8X0gygNmnZdt4crzWmkWlB7TQzx0EOU8NB7ngqHJTaFPe0eqxWDIKOH5s8AXA4\n"
    "u2+8N93cT7vH7Y3afIISjIrgyV1HmpfYSjAj+rO6LUktAgED\n"
    "-----END PUBLIC KEY-----\n";

#endif /* OECERT_ENC_PUBLIC_KEY */
```

### PR DESCRIPTION
**Pull request by qiucwang**
Fixes #3980 
Add a lock for oecert/gen_pubkey_header.sh and check lock before modify the oecert_enc_pubkey.h

Signed-off-by: Qiucheng Wang <qiucwang@microsoft.com>

### CODE REVIEW

File: tools/oecert/gen_pubkey_header.sh [hunk 1]
```diff
@@ -3,9 +3,18 @@
...
 destfile="$1"
 pubkey_file="$2"
 
+#Check locks for oecert/gen_pubkey_header.sh
+if [ -f "$lock" ]; then
+    echo "oecert_enc_pubkey.h is being written"
+    exit 1
+fi
+
+# add lock
```
Comment (mingweishih) [inline tools/oecert/gen_pubkey_header.sh:16]:
```suggestion
# Create the lock
```

File: tools/oecert/gen_pubkey_header.sh [hunk 2]
```diff
@@ -29,3 +38,6 @@ cat >> "$destfile" << EOF
 
 #endif /* OECERT_ENC_PUBLIC_KEY */
 EOF
+
+# remove lock
```
Comment (mingweishih) [inline tools/oecert/gen_pubkey_header.sh:42]:
```suggestion
# Remove the lock
```

**Review by mingweishih — APPROVED** [review]
LGTM with some minor comments. Thanks for the fix!

**Comment by mingweishih** [comment]
bors try

File: tools/oecert/gen_pubkey_header.sh [hunk 3]
```diff
@@ -3,9 +3,18 @@
 # Copyright (c) Open Enclave SDK contributors.
 # Licensed under the MIT License.
 
+lock="/var/tmp/oecert_lock"
 destfile="$1"
 pubkey_file="$2"
 
+# Check if the lock exists
+if [ -f "$lock" ]; then
```
Comment (yentsanglee) [inline tools/oecert/gen_pubkey_header.sh:11]: Also check if $destfile exists. If so, exit. This prevents header files from being generated multiple times.

Comment (yentsanglee) [reply tools/oecert/gen_pubkey_header.sh:11]: Hmm.. there could be a potential issue if header file from old key lingers.

**Review by yentsanglee — APPROVED** [review]
