### PR TITLE
Make in-enclave pthread_mutex not recursive by default and support pthread_mutexattr APIs

### LINKED ISSUE #4555: `std::mutex` implementation is broken
`std::mutex` can be locked multiple times in succession in OE SGX enclaves.

Minimal repro is something like this:

```diff
diff --git a/tests/threadcxx/enc/enc.cpp b/tests/threadcxx/enc/enc.cpp
index f116c9051..0f2f10b96 100644
--- a/tests/threadcxx/enc/enc.cpp
+++ b/tests/threadcxx/enc/enc.cpp
@@ -56,6 +56,16 @@ static std::atomic<size_t> test_mutex_count2(0);
 
 void enc_test_mutex_cxx()
 {
+    {
+        std::mutex mut;
+        mut.lock();
+        mut.lock();
+        if (mut.try_lock())
+        {
+            abort();
+        }
+    }
+
     std::stringstream ss;
 
     recursive_mutex1.lock();
```

Obviously the second `mut.lock()` should block (it doesn't), and a subsequent `try_lock()` should fail (it succeeds).

### PR DESCRIPTION
**Pull request by mingweishih**
Previously, the oe_mutex implementation supports only the recursive mutex type by default and there is no way to opt out.
This PR updates the internal oe_mutex implementation so that the mutex is not recursive by default. In addition, the PR implements the oe_mutexattr* APIs (will be used by pthread_mutexattr* APIs), allowing for initializing mutex with normal or recursive type.

Note that with the PR, consecutive oe_mutex_lock on a non-recursive lock will result in a deadlock. OE additionally provides logging to help debugging.

Fixes #4555

Signed-off-by: Ming-Wei Shih <mishih@microsoft.com>

### CODE REVIEW

**Comment by mingweishih** [comment]
bors try

**Comment by mingweishih** [comment]
bors try-

**Comment by mingweishih** [comment]
bors try

File: enclave/core/sgx/thread.c [hunk 1]
```diff
@@ -167,35 +167,109 @@ typedef struct _oe_mutex_impl
...
+done:
     return result;
 }
 
 /* Caller manages the spinlock */
 static int _mutex_lock(oe_mutex_impl_t* m, oe_sgx_td_t* self)
 {
     /* If this thread has already locked the mutex */
-    if (m->owner == self)
+    if (m->owner == self && m->type == OE_MUTEX_RECURSIVE)
```
Comment (anakrish) [inline enclave/core/sgx/thread.c:270]: It would be good to detect recursive lock of a non-recursive mutex. In addition to logging it, should we also abort?

**Review by anakrish — COMMENTED** [review]
Though this fixes incorrect behavior, this PR changes the behavior of public API (pthread_mutex_lock) in OE. This needs to be called out in the changelist.

**Comment by achamayou** [comment]
Could testcases for std::mutex and std::recursive_mutex be added, since Open Enclave ships libcxx and this is where the break had impact?

**Comment by mingweishih** [comment]
> Could testcases for std::mutex and std::recursive_mutex be added, since Open Enclave ships libcxx and this is where the break had impact?

The existing threadcxx test should cover these two already.

**Comment by achamayou** [comment]
@mingweishih I don't understand how that's possible, they've been passing as far as I can tell, despite std::mutex very clearly doing the wrong thing: https://github.com/openenclave/openenclave/issues/4555 - what am I missing?

**Comment by mingweishih** [comment]
> @mingweishih I don't understand how that's possible, they've been passing as far as I can tell, despite std::mutex very clearly doing the wrong thing: #4555 - what am I missing?

I added two trylock call after mutex for the threadcxx test in this PR to cover the case of std::mutex.
The std::recursive_mutex testing code is in the test already, and hence no change required. Are you thinking of something more?

Given that the two consecutive std::mutex would result in deadlock, I didn't add such test code in this PR.

**Comment by mingweishih** [comment]
@achamayou @anakrish 
Per #4555, with the PR, consecutive std::mutex will result in a deadlock. OE additionally provides logging to help debugging.

provides log when deadlock occurs.

**Comment by mingweishih** [comment]
bors try

File: enclave/core/sgx/thread.c [hunk 2]
```diff
@@ -242,8 +325,18 @@ oe_result_t oe_mutex_lock(oe_mutex_t* mutex)
...
+            if (result == OE_BUSY)
+            {
+                /* Deadlock */
+                OE_TRACE_ERROR("Recursively acquire a non-recursive lock");
+                continue;
+            }
+
+            if (result == OE_OK)
             {
+                /* Successfully aquire the lock */
```
Comment (jbdelcuv) [inline enclave/core/sgx/thread.c:339]: This minor comment is for line 348 below, which is not included in this PR, but could you fix the indentation?

**Review by jbdelcuv — APPROVED** [review]
Looks good to me.

**Comment by achamayou** [comment]
> I added two trylock call after mutex for the threadcxx test in this PR to cover the case of std::mutex.

@mingweishih my bad, I'd missed those. Thank you.

File: enclave/core/sgx/thread.c [hunk 3]
```diff
@@ -167,65 +167,148 @@ typedef struct _oe_mutex_impl
...
+
+oe_result_t oe_mutexattr_init(oe_mutexattr_t* attr)
+{
+    oe_mutexattr_impl_t* attr_impl = (oe_mutexattr_impl_t*)attr;
+    oe_result_t result = OE_FAILURE;
+
+    if (!attr_impl)
+        OE_RAISE(OE_INVALID_PARAMETER);
+
+    attr_impl->type = OE_MUTEX_DEFAULT;
```
Comment (anakrish) [inline enclave/core/sgx/thread.c:213]: To be consistent with oe_mutex_init, the entire oe_mutexattr_t struct needs to be set to zero. If we set only the `type` field, other portions of the struct could have random value.

File: enclave/core/sgx/thread.c [hunk 4]
```diff
@@ -242,8 +325,18 @@ oe_result_t oe_mutex_lock(oe_mutex_t* mutex)
         oe_spin_lock(&m->lock);
         {
             /* Attempt to acquire lock */
-            if (_mutex_lock(m, self) == 0)
+            oe_result_t result = _mutex_lock(m, self);
+
+            if (result == OE_BUSY)
+            {
+                /* Deadlock */
+                OE_TRACE_ERROR("Recursively acquire a non-recursive lock");
```
Comment (anakrish) [inline enclave/core/sgx/thread.c:333]: Would this print the trace message in each iteration?

File: tests/threadcxx/enc/enc.cpp [hunk 5]
```diff
@@ -89,6 +89,7 @@ static void _test_mutex1_cxx(size_t* count)
     std::stringstream ss;
 
     mutex1.lock();
+    OE_TEST(!mutex1.try_lock());
```
Comment (anakrish) [inline tests/threadcxx/enc/enc.cpp:92]: According to standard, just like lock, try_lock also has undefined behavior:
https://en.cppreference.com/w/cpp/thread/mutex/try_lock

File: enclave/core/sgx/thread.c [hunk 6]
```diff
@@ -167,65 +167,148 @@ typedef struct _oe_mutex_impl
...
 
+done:
     return result;
 }
 
 /* Caller manages the spinlock */
-static int _mutex_lock(oe_mutex_impl_t* m, oe_sgx_td_t* self)
+static oe_result_t _mutex_lock(oe_mutex_impl_t* m, oe_sgx_td_t* self)
 {
+    oe_result_t result = OE_NOT_OWNER;
```
Comment (anakrish) [inline enclave/core/sgx/thread.c:269]: OE_NOT_OWNER is not defined anywhere. It is better to not introduce a new error enum that the user will never see.

File: enclave/core/sgx/thread.c (hunk 4 above)
Comment (mingweishih) [reply enclave/core/sgx/thread.c:333]: No, the execution will proceed to call the oe_spin_lock above again and hang.

File: tests/threadcxx/enc/enc.cpp (hunk 5 above)
Comment (mingweishih) [reply tests/threadcxx/enc/enc.cpp:92]: I was based on https://linux.die.net/man/3/pthread_mutex_trylock, which mentions
> The pthread_mutex_trylock() function shall be equivalent to pthread_mutex_lock(), except that if the mutex object referenced by mutex is currently locked (by any thread, including the current thread), the call shall return immediately.

Also I just come across the code snippet in https://www.enseignement.polytechnique.fr/informatique/INF478/docs/Cpp/en/cpp/thread/mutex/unlock.html,
which also uses try_lock to determine if the mutex is locked or not.

File: enclave/core/sgx/thread.c (hunk 6 above)
Comment (mingweishih) [reply enclave/core/sgx/thread.c:269]: This was defined in https://github.com/openenclave/openenclave/blob/d68c5f363f7cbafc1c396d296b0557c212e6d9ef/include/openenclave/bits/result.h#L202

File: enclave/core/sgx/thread.c (hunk 2 above)
Comment (mingweishih) [reply enclave/core/sgx/thread.c:339]: Thanks for the review. Can you point me what's the exact line of code you refers to given that line number is changing over time.

File: tests/threadcxx/enc/enc.cpp (hunk 5 above)
Comment (anakrish) [reply tests/threadcxx/enc/enc.cpp:92]: I don't think that is standards conforming behavior. A precondition for both lock and unlock operations of a mutex type is that the calling thread does not own the mutex:
http://www.eel.is/c++draft/thread.mutex.requirements

Comment (mingweishih) [reply tests/threadcxx/enc/enc.cpp:92]: I agree with it.
cc @achamayou @eddyashton 
Can you provide inputs on what's the expected behavior you want? It appears that it's inappropriate to reply on trylock() to test std::mutex.

Comment (mingweishih) [reply tests/threadcxx/enc/enc.cpp]: Removed the use of try_lock() in the tests.

File: enclave/core/sgx/thread.c [hunk 7]
```diff
@@ -167,65 +167,148 @@ typedef struct _oe_mutex_impl
...
+
     /* If this thread has already locked the mutex */
     if (m->owner == self)
     {
-        /* Increase the reference count */
-        m->refs++;
-        return 0;
+        if (m->type != OE_MUTEX_RECURSIVE)
+        {
+            OE_RAISE(OE_BUSY);
```
Comment (anakrish) [inline enclave/core/sgx/thread.c:278]: Should this be OE_RAISE_NO_TRACE since the caller is responsible for printing the message?

**Review by anakrish — APPROVED** [review]
LGTM.
