### PR TITLE
Fix crypto crl test time diffing

### LINKED ISSUE #2617: tests/crypto tests fail transiently: oe_result_t=OE_VERIFY_REVOKED crl_tests.c_test_get_dates last.minutes == _time.minutes
The CRL test in tests/crypto fails (very rarely) because a cert generated on a minute boundary may have a different "cert issued" time and "file created" time.

We should create a tolerance function for minute/hour/day/month/second boundaries so that as long as the times are within a reasonable interval (30 sec?) the test will still pass.

This issue causes failures in CI which should be as reliable as possible.

### PR DESCRIPTION
**Pull request by jhand2**
The time diffing in the crypto CRL test is error prone to transient changes in the timestamp when the test was run. Modify the test to use a tolerance function to figure out the diff between two datetimes.

Fixes #2617

### CODE REVIEW

**Comment by jhand2** [comment]
bors try

**Comment by jhand2** [comment]
Open to a smaller tolerance. 5 seconds is probably fine

**Comment by jhand2** [comment]
Huh, either my diff function is broken or the certs really are far apart: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAgnostic-Linux/detail/Agnostic-Linux/527/pipeline/25

I'll look into it later

**Comment by jhand2** [comment]
Huh, either my diff function is broken or the certs really are far apart: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAgnostic-Linux/detail/Agnostic-Linux/527/pipeline/25

I'll look into it later. Trying again for now

bors try

File: tests/crypto/crl_tests.c [hunk 1]
```diff
@@ -139,22 +152,17 @@ static void _test_get_dates(void)
...
-    OE_TEST(last.day == _time.day);
-    OE_TEST(last.hours == _time.hours);
-    OE_TEST(last.minutes == _time.minutes);
-    // TEMPORARILY Disabled: _time is the certificate file's timestamp
-    // whereas last.seconds is the actual issue time of the certificate.
-    // The two values are not guaranteed to be equal.
-    // OE_TEST(last.seconds == _time.seconds);
+    int32_t diff = _diff_oe_datetime(&last, &_time);
+    printf("=== Diff between last and current time: %d\n", diff);
+    OE_TEST(abs(diff) < 60); // Ensure times are within 60 seconds
```
Comment (dthaler) [inline tests/crypto/crl_tests.c:157]: Suggest creating a #define'd constant that you can use here and in line 216 rather than hard coding 60 in both places.   And is the number 60 arbitrary or is there a reason it's better than say 10 or 300?

Comment (jhand2) [reply tests/crypto/crl_tests.c:157]: It's arbitrary. I'm open to changing it, I wanted to experiment with what the value normally is, although it my local testing it's pretty much always 0 or 1

File: tests/crypto/crl_tests.c [hunk 2]
```diff
@@ -127,6 +127,19 @@ static bool _year_is_a_leap_year(uint32_t year)
     }
 }
 
+static int32_t _diff_oe_datetime(oe_datetime_t* t1, oe_datetime_t* t2)
+{
+    int32_t dyear = (int32_t)t1->year - (int32_t)t2->year;
+    int32_t dmonth = (int32_t)t1->month - (int32_t)t2->month;
```
Comment (anakrish) [inline tests/crypto/crl_tests.c:133]: For a correct `diff` of date time won't there be logic to handle the varying lengths of different months, leap years etc?

File: tests/crypto/crl_tests.c (hunk 1 above)
Comment (anakrish) [inline tests/crypto/crl_tests.c:157]: If the tolerance needs to in minutes can we instead just add the tolerance to the check that compares the minutes?:

`OE_TEST( abs((int32_t)last.minutes -_(int32_t)time.minutes) <= 1)`;

File: tests/crypto/crl_tests.c [hunk 3]
```diff
@@ -127,6 +127,19 @@ static bool _year_is_a_leap_year(uint32_t year)
...
+    int32_t dday = (int32_t)t1->day - (int32_t)t2->day;
+    int32_t dhour = (int32_t)t1->hours - (int32_t)t2->hours;
+    int32_t dmin = (int32_t)t1->minutes - (int32_t)t2->minutes;
+    int32_t dsec = (int32_t)t1->seconds - (int32_t)t2->seconds;
+
+    return (dyear * 31556952) + (dmonth * 2592000) + (dday * 86400) +
```
Comment (CodeMonkeyLeet) [inline tests/crypto/crl_tests.c:139]: These are date-time values and not cumulative time values, so individual elements in t1 may be less that individual elements in t2, resulting in the addition of negative numbers. If you want to do this, you'd need to do the conversion to cumulative time first, and then the diff

It doesn't necessarily matter in the use case here, but really it seems like you should implement a specific boundary limit function instead of implementing a generic datetime diff function. i.e. in `_test_get_dates()` call `oe_datetime_compare()` and if they are not equal, then you only have to deal with checking that your min + sec difference is within your expected time bound.

File: tests/crypto/crl_tests.c (hunk 2 above)
Comment (dthaler) [reply tests/crypto/crl_tests.c:133]: Actually that's a great point.  A safer algorithm would be to convert to time_t (using mktime or whatever) and then take the difference in seconds.

File: tests/crypto/crl_tests.c (hunk 1 above)
Comment (jhand2) [reply tests/crypto/crl_tests.c:157]: minute 1, second 59
minute 2, second 1

How far apart are these?

Comment (jhand2) [reply tests/crypto/crl_tests.c:157]: Tolerance is in seconds. 60 was a random choice, a much smaller number would be ideal

File: tests/crypto/crl_tests.c (hunk 3 above)
Comment (jhand2) [reply tests/crypto/crl_tests.c:139]: Dave's suggestion to convert to time_t is probably easier. I'll look into that.

**Comment by johnkord** [comment]
Last night I was bored and I came across this PR, so I've added a friendly amendment to @jhand2 's branch that addresses some of these comments (this is, after all, related to my pet interview question). Feel free to accept the changes to your branch, @jhand2  or do what you wish with them! :)

https://github.com/jhand2/openenclave/pull/1

### Testing Notes
(Tested on Ubuntu 18.04 with no SGX as well as on Windows 10 with SGX1. I think there's a new Jenkins instance and I don't have access to the Sandbox there, so I can't give this branch a run through. I think this branch may need to be rebased on master to work on Windows, though)

**Comment by jhand2** [comment]
bors try

**Comment by jhand2** [comment]
Thanks @johnkord! I merged you PR into this branch.

**Comment by CodeMonkeyLeet** [comment]
@dthaler I believe that your comment was addressed, can you review and remove your change request on this PR?

**Comment by radhikaj** [comment]
Bors r+
